### ISSUE TITLE
Provide a better status report for multiple recordings

### ISSUE THREAD

**Issue by ergunsh** [puppeteer/replay#133]
Recorder panel and `@puppeteer/replay` library makes it a lot easier to start writing E2E tests. For a small project of mine, I was able to have a basic E2E setup using Recorder panel in around 5 minutes :)

Though currently running multiple files doesn't provide a good status report at the end: i.e. these replays succeeded and this failed with reason X.

So, if we provide a better status report; users will be able to use this as a basic recorder runner maybe to have their initial tests in their codebase.

**Comment by OrKoN** [comment]
I believe you can specify a directory using shell expansion. E.g., `replay test/resources/*.json`. Alternatively, one can use xargs and similar utilities together with `find` or `ls`. I am not sure if we really should support glob parsing inside the lib. Adding some improved reporting sounds good to me.

**Comment by ergunsh** [comment]
Oh, yes; you're totally right and we have the ability to specify multiple files with shell expansion. I'm updating this as a feature request for better reporting :)

**Comment by Lowlife84** [comment]
> Recorder panel and `@puppeteer/replay` library makes it a lot easier to start writing E2E tests. For a small project of mine, I was able to have a basic E2E setup using Recorder panel in around 5 minutes :)
> 
> Though currently running multiple files doesn't provide a good status report at the end: i.e. these replays succeeded and this failed with reason X.
> 
> So, if we provide a better status report; users will be able to use this as a basic recorder runner maybe to have their initial tests in their codebase.

https://github.com/puppeteer/replay/issues/133#issue-1235181301

**Comment by nickmccurdy** [comment]
This seems to have been fixed by #224.
