### ISSUE TITLE
Add `BASE_URL` support

### ISSUE THREAD

**Issue by puskuruk** [puppeteer/replay#146]
When you have multiple environments you might want to run your tests with different base URLs for each environment. For example:

```
BASE_URL=http://www.staging.your-awesome-application.com npx @puppeteer/replay recording.json
```
```
BASE_URL=http://www.test.your-awesome-application.com npx @puppeteer/replay recording.json
```

**Comment by OrKoN** [comment]
Hey, thanks for the feature request. How would it work if the recording involves multiple domains? I guess using this variable might result in a broken recording in that case?

**Comment by puskuruk** [comment]
Thank you @OrKoN 

Yes, when you have multiple domains it'll fail. In our case we deploy our application to different environments and I wanted be able to test those environments with replacing base URLs.

How we can improve this implementation?

**Comment by OrKoN** [comment]
@puskuruk I think it'd be nice to allow importing custom runner extensions so that use case/app-specific logic could be implemented. But I think it's something that we need to take a look into!

**Comment by puskuruk** [comment]
Yes, I also solved this problem in our codebase with writing an extension but I thought using an environment variable is more straightforward solution.

I can implement this feature 🙏

**Comment by puskuruk** [comment]
In our codebase,I solved this problem with a custom runner but I thought using an environment variable is more straightforward solution. Because it's a common practice.

[https://playwright.dev/docs/test-advanced](https://playwright.dev/docs/test-advanced)
[https://docs.cypress.io/guides/references/best-practices#Setting-a-global-baseUrl](https://docs.cypress.io/guides/references/best-practices#Setting-a-global-baseUrl)

```js
/**
 * Run a recording from a json file
 * @param {string} recordingPath
 * @param {Extension} extension
 */
async function runRecording(recordingPath, extension) {
  const content = await fs.readFile(recordingPath, 'utf8');
  const object = JSON.parse(content);
  const recordingWithBaseURL = addBaseURLToRecording(object);

  const recording = parse(recordingWithBaseURL);
  const runner = await createRunner(recording, extension);

  await runner.run();
}
```

But importing custom runner extensions also makes sense, and I can implement this feature 🙏

**Comment by s4l4x** [comment]
The issue for us is that the starting url may and usually is different from where we want to run the tests. This wouldn't be an issue if we were only testing production, but we test PRs, development, staging, and local environments, all with different URLs. This allows us to catch bugs before going to production. 

It seems like there is an implicit starting url with the first navigate step. One idea would be if there's a `BASE_URL` defined, then we could override the starting url of a recording's first step and any subsequent URL bases which match the starting URL. Something like this: 

Recording 1 
```
steps: [
    {
      "type": "navigate",
      "url": "http://localhost:3001/doawesome",
      ...
    },
    ...
    {
      "type": "navigate",
      "url": "http://someotherurl.com",
      ...
    },
    ...
    {
      "type": "navigate",
      "url": "http://localhost:3001/doawesome",
      ...
    },
]
```

Recording 2 
```
steps: [
    {
      "type": "navigate",
      "url": "http://localhost:3008/doawesome",
      ...
    },
    ...
    {
      "type": "navigate",
      "url": "http://someotherurl.com",
      ...
    },
    ...
    {
      "type": "navigate",
      "url": "http://localhost:3008/doawesome",
      ...
    },
]
```

With a `BASE_URL = website.ftw` these would become: 

Recording 1 
```
steps: [
    {
      "type": "navigate",
      "url": "http://website.ftw/doawesome",
      ...
    },
    ...
    {
      "type": "navigate",
      "url": "http://someotherurl.com",
      ...
    },
    ...
    {
      "type": "navigate",
      "url": "http://website.ftw/doawesome",
      ...
    },
]
```

Recording 2 
```
steps: [
    {
      "type": "navigate",
      "url": "http://website.ftw/doawesome",
      ...
    },
    ...
    {
      "type": "navigate",
      "url": "http://someotherurl.com",
      ...
    },
    ...
    {
      "type": "navigate",
      "url": "http://website.ftw/doawesome",
      ...
    },
]
```

Thoughts on this approach?

**Comment by puskuruk** [comment]
Since we have a solution to modify URLs with extension we can close this issue. 🙏 

Example implementation:
```js
const { PuppeteerRunnerExtension } = require('@puppeteer/replay')

class Extension extends PuppeteerRunnerExtension {
  async runStep(step, flow) {
    if ('url' in step) {
      // modify URL here
      // reassign step here
    }

    await super.runStep(step, flow)
  }
}
```
