### ISSUE TITLE
Jest Integration

### ISSUE THREAD

**Issue by NateAGeek** [puppeteer/replay#188]
I ideally would like to add this project and use it for my e2e unit tests, using jest. I've come into the issue of getting Jest to play nicely with the cjs version of the project. However, I am curious if we could add documentation or better accommodate Jest support?

**Comment by OrKoN** [comment]
Could you please describe what problems are you facing with jest? Theoretically, there should be no issues just because of Jest.

**Comment by NateAGeek** [comment]
I think @adamraine merge, make cjs the main entry point, might actually make the issue I was facing resolved. Since the current library uses ESM version as entry point, Jest errors out. Jest is not really compatible with ESM, without some configuration tweaks. Also, I had to require the full path for cjs, and I did loose typing info along the way. But now I think this should be resolved. I'll test and confirm, thank you.

**Comment by NateAGeek** [comment]
Yep, the new cjs main entry resolved my issue, thank you @adamraine!
