### ISSUE TITLE
Step Delay Property

### ISSUE THREAD

**Issue by NateAGeek** [puppeteer/replay#189]
Add Step Delay Property

I think it would be useful for allowing the user to set a step delay between each step. This can help seeing step by step what could cause the issue.

**Comment by puskuruk** [comment]
I mostly use a sleep(`await  new Promise((resolve, reject) => { setTimeout(() => resolve(), 2000) })`) function on `beforeEachStep`. But you can also use a sleep function in your JSON file as a step:
```JSON
{
  "type": "waitForExpression",
  "expression": "new Promise(resolve => setTimeout(() => resolve(true), 2000))"
},
```

**Comment by puskuruk** [comment]
I mostly use a sleep(`await  new Promise((resolve, reject) => { setTimeout(() => resolve(), 2000) })`) function on `beforeEachStep` in my custom extensions. But you can also use a sleep function in your JSON file as a step:
```JSON
{
  "type": "waitForExpression",
  "expression": "new Promise(resolve => setTimeout(() => resolve(true), 2000))"
},
```

Also there is a `slowMo` option in puppeteer itself.
[https://developers.google.com/web/tools/puppeteer/debugging](https://developers.google.com/web/tools/puppeteer/debugging)

**Comment by NateAGeek** [comment]
Ah, thank you! I was doing the delays in the inline in the json. However, I do think it would be nice to have a setting, however, the `beforeEachStep` is a good solution. Thank you again!
