### ISSUE TITLE
Missing dependency: lighthouse

### ISSUE THREAD

**Issue by rlaffers** [puppeteer/replay#334]
## Expected Behavior

The @puppeteer/replay is compiled without errors when it is installed as a dependency.

## Actual Behavior
An error occurs when I bundle my app:
> [vite]: Rollup failed to resolve import "lighthouse/core/fraggle-rock/api.js" from "node_modules/@puppeteer/replay/lib/main.js".

This is due to lighthouse missing from the **dependencies** and/or **peerDependencies** in package.json. `lighthouse` is listed only as a devDependency, while in fact it is a normal dependency since the library source depends on it.

## Steps to Reproduce the Problem

1. npm create vite@latest my-app -- --template vanilla
1. cd my-app && npm install
1. npm install --save @puppeteer/replay
2. Import from @puppeteer/replay in the main.js file:
  `import { PuppeteerRunnerExtension } from '@puppeteer/replay'`
1. npm run build

## Specifications

- Version: @puppeteer/replay@1.3.1, node 16.18.0
- Platform: Linux

**Comment by OrKoN** [comment]
@adamraine could you please take a look?

**Comment by adamraine** [comment]
So we prevent Lighthouse from being bundled using rollup externals:

https://github.com/puppeteer/replay/blob/961965eb6dfffd02191cbc6fee311df899ca1d7e/rollup.config.cjs#L20

I would expect tree shaking prevent rollup from using `LighthouseRunnerExtension` and therefore remove the need to import Lighthouse.

In any case, we should remove the lighthouse runner extension from the main bundle. Eventually we will make Lighthouse a peer dependency, but Lighthouse needs a lot of work with rollup plugins to work in bundled environments. If rollup can't automatically trim the Lighthouse import statements, maybe we should add a separate import path for Lighthouse like `@puppeteer/replay/lighthouse`.
