### ISSUE TITLE
Lighthouse tests take too long

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/replay#344]
Currently, it seems that Lighthouse tests take 30sec each. Is there a way to reduce this time?

**Comment by OrKoN** [comment]
@adamraine I would appreciate any input from your side!

**Comment by OrKoN** [comment]
The tests added in #275 take <= 1.5 sec each but Lighthouse tests take more than 30sec each. I guess the bottleneck here is not the replay itself but rather the audit time? Is it possible to shorten how long it takes to audit a flow?

**Comment by adamraine** [comment]
> The tests added in https://github.com/puppeteer/replay/issues/275 take <= 1.5 sec each but Lighthouse tests take more than 30sec each. I guess the bottleneck here is not the replay itself but rather the audit time?

Correct. I wasn't suggesting that the replay is slow, Lighthouse is definitely the bottleneck. However, our options for reducing the test duration are somewhat limited if we want the e2e test to be valuable. In a best case scenario, we could get each test down to 15-20s which is still very long.

IMO we need to live with the long test times somehow. This is why I was suggesting a separate e2e test runner so e2e tests don't force the unit test runner to stall. Moving the tests from #275 into this new e2e runner would make sense organizationally.

> Is it possible to shorten how long it takes to audit a flow?

Yes it is possible, we should pursue the bullet points in my previous comment.

**Comment by OrKoN** [comment]
> IMO we need to live with the long test times somehow. This is why I was suggesting a separate e2e test runner so e2e tests don't force the unit test runner to stall. Moving the tests from https://github.com/puppeteer/replay/issues/275 into this new e2e runner would make sense organizationally.

let's move Lighthouse to e2e tests then! I will do that. I would keep other tests in the "unit" test ran as it allows quickly iterating locally and detecting breaking changes.
