### ISSUE TITLE
Can you add a step to type a string text in a contenteditible element?

### ISSUE THREAD

**Issue by jonascript** [puppeteer/replay#379]
Currently with the replay scriptRunner, we can only enter an element with a "keyDown" which only does one key at a time, however these days many apps and plugins like prose mirror use contenteditable which means we can't use the "change" step which assumes an input.

Would you consider adding the "page.type" as a step type? Without something like this to type into contenteditable elements, the framework's usefulness becomes limited but with this it will be incredibly useful.
https://pptr.dev/api/puppeteer.page.type/

Alternatively, enabling the ability to add our own custom steps would be great. I saw something in the docs about a custom step but it looks like it hasn't been implemented.

**Comment by OrKoN** [comment]
@jonascript we'd rather make `change` work with contenteditable. Would that cover your use case?

**Comment by jonascript** [comment]
Thanks @OrKoN. That should cover my use case, however, FWIW in puppeteer the function call used is element.type()

This is the function below I'm using to do this. 

```
  async function typeTextIntoElement(selector, text) {
    {
      const targetPage = page;
      const element = await waitForSelectors([[selector]], targetPage, {
        timeout,
        visible: true,
      });
      await scrollIntoViewIfNeeded(element, timeout);
      const isContentEditable = await element.evaluate((el) =>
        el.getAttribute('contenteditable')
      );
      if (isContentEditable) {
        return await element.type(text);
      }
      const type = await element.evaluate((el) => el.type);
      if (['select-one'].includes(type)) {
        await element.select(text);
      } else if (
        [
          'textarea',
          'text',
          'url',
          'tel',
          'search',
          'password',
          'number',
          'email',
        ].includes(type)
      ) {
        await element.type(text);
      } else {
        await element.focus();
        await element.evaluate((el, value) => {
          el.value = value;
          el.dispatchEvent(new Event('input', { bubbles: true }));
          el.dispatchEvent(new Event('change', { bubbles: true }));
        }, text);
      }
    }
  }
```

**Comment by OrKoN** [comment]
This has been implemented now via the Locator API in Puppeteer.
