### ISSUE TITLE
How to slow it down?

### ISSUE THREAD

**Issue by RaeesBhatti** [puppeteer/replay#411]
## Expected Behavior
A user can configure a delay between steps when running a flow.

## Actual Behavior
Replay script has no apparent option to configure the delay between steps. Sometimes the transition between pages or steps is too fast and breaks expectations causing flakiness in tests.

## Steps to Reproduce the Problem

1. Record a flow in Chrome Dev Tools
1. Download the flow as Replay script
1. Run the script

## Specifications

- Version:
- Platform:

**Comment by OrKoN** [comment]
You can use `waitForExpression` with a setTimeout inside to slow down the replay. In general, it will lead to more flakiness and is not encouraged. It's better to figure out if the right preconditions for an action exist: such as the element is visible and present (which replay lib does by default) or custom conditions that could be implemented with waitForElement and waitForExpression steps.
