### ISSUE TITLE
Error when loading the recorder chrome extension

### ISSUE THREAD

**Issue by PeterNgTr** [puppeteer/replay#453]
## Expected Behavior
Can use the extension normally

## Actual Behavior
![Screenshot 2023-01-31 at 17 20 09](https://user-images.githubusercontent.com/7845001/216021114-78fcb110-b46a-435e-8b77-8790d9c6117e.png)

## Steps to Reproduce the Problem

1. Install the extension https://chrome.google.com/webstore/detail/codeceptjs-chrome-recorde/ojkfinikejhpchjenhafdlcmgaiaaclg
2. Try to export the steps after the recording

source code: 
https://github.com/PeterNgTr/codeceptjs-recorder-extension
https://github.com/PeterNgTr/codeceptjs-chrome-recorder

**Comment by OrKoN** [comment]
Hey, it looks like you are not rolling up the JS code in the extension.

**Comment by PeterNgTr** [comment]
@OrKoN could you show me the documentation or some leads that I may follow? First time developing the extension so you know. 😸

**Comment by OrKoN** [comment]
I have built the version locally from https://github.com/PeterNgTr/codeceptjs-recorder-extension and it works fine for me except from two problems: 1) icons are missing: defined in the manifest but no icon files 2) the published extension error looks like a problem with the code that was uploaded: it looks like source was uploaded instead of the dist folder.

**Comment by OrKoN** [comment]
<img width="569" alt="Screenshot 2023-02-01 at 12 40 59" src="https://user-images.githubusercontent.com/399150/216033001-1fe3901b-9b20-49e5-b605-7ddc35ee6b26.png">

**Comment by PeterNgTr** [comment]
Thanks @OrKoN for looking into it. I sorted out the issue. Will try another publishing.

**Comment by PeterNgTr** [comment]
Hi @OrKoN out of curiosity, this preview is coming from Chrome itself or anything I could make to have this feature on. Looks convenient for me. 

![image](https://user-images.githubusercontent.com/7845001/219931649-bdb40949-15fd-4d11-a10a-6fb40fb7a3a1.jpeg)

**Comment by OrKoN** [comment]
The preview is a Chrome feature, no need for additional actions. I think it was released in Chrome 110.
