### ISSUE TITLE
Replay w Extension in Chrome Dev Tools

### ISSUE THREAD

**Issue by rpgit12** [puppeteer/replay#539]
I'm able to extend the puppeteer with a custom replay extension, and now would like to use that inside Chrome dev tools (as Replay Extension.) Is that possible?

**Comment by OrKoN** [comment]
See an example of a replay extension for Chrome https://github.com/puppeteer/replay/tree/main/examples/chrome-extension-replay You will need a server (local or remote) to run the recording from within the DevTools.

**Comment by rpgit12** [comment]
@OrKoN  - thank you!
