### ISSUE TITLE
How does the devtools recorder connect to my manually launched browser without specifying debug port

### ISSUE THREAD

**Issue by Fly-Playgroud** [puppeteer/replay#552]
As this [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1447444) mentioned, in chrome recorder  the recorder how to know `--remote-debuggin-port`  without specifying this parameter, and let Puppeteer and  Puppeteer-replay connnect running chrome.
Chrome recorder only needs to press the single button just connect chrome browser.
 I want to know how it is able to do this, specifically, how it retrieves the -remote-debugging-port of the currently running Chrome instance.
![image](https://github.com/puppeteer/replay/assets/61271333/e801aa04-de2a-4c7a-a67e-a0336246f593)

**Comment by OrKoN** [comment]
Recorder does not use websockets so it does not use a remote debugging port and no web socket server is started. Recorder panels connects via CDP bindings exposed to the DevTools frontend renderer. See the source code for more details https://source.chromium.org/chromium/chromium/src/+/main:third_party/devtools-frontend/src/front_end/panels/recorder/

**Comment by Fly-Playgroud** [comment]
> Recorder does not use websockets so it does not use a remote debugging port and no web socket server is started. Recorder panels connects via CDP bindings exposed to the DevTools frontend renderer. See the source code for more details https://source.chromium.org/chromium/chromium/src/+/main:third_party/devtools-frontend/src/front_end/panels/recorder/

Which specific file and codes are you referring to, or where can we find a detailed design document about this particular area?
