### ISSUE TITLE
Custom extension is not reflecting in export option

### ISSUE THREAD

**Issue by bawarim** [puppeteer/replay#611]
Hi Team,

I have created my own custom extension to export dev tool recording files.
I am able to add an extension using the load unpacked option, but I am not getting my custom extension in the export recording list.

Could you please help?

**Comment by bawarim** [comment]
Yes, I am able to load the example extension. 
I observed that, when I am writing below code in DevToolsPlugin.js to use my custom method. Then I am not able to see it on export file option. 

import {
  specflowStringifyChromeRecording,
  stringifyParsedStep
} from "../mycustom-chrome-recorder-main/src/main.js";

**Comment by OrKoN** [comment]
check chrome://extensions page, you likely have import errors. Make sure you custom files are inside the extension root, otherwise, they won't be loaded.

**Comment by bawarim** [comment]
No, I am not getting any import errors on chrome://extensions page. I have added my custom files inside the extension root also. 
But that didn't work as well.
