### ISSUE TITLE
It should be considered to add a serial number to the exported step in json, and provide clear error steps when recording execution fails

### ISSUE THREAD

**Issue by saltires** [puppeteer/replay#697]
## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:

**Comment by OrKoN** [comment]
Could you provide more details about your use case? the steps are already ordered and for improved error handling there is an issue filed already https://github.com/puppeteer/replay/issues/81

**Comment by 775580833** [comment]
اريد اصلاح الهاتف الرقم التسلسلي مفقود860325062893409

**Comment by 775580833** [comment]
لاتوجدشبكه

**Comment by 775580833** [comment]
اريد اضافة الرقم التسلسلي860325062893409
