### ISSUE TITLE
localFrame.locator is not a function

### ISSUE THREAD

**Issue by SujaanKanwar** [puppeteer/replay#780]
## Expected Behavior
replay script should be running
## Actual Behavior
It breaks
## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:

**Comment by OrKoN** [comment]
Which Puppeteer version are you using? Make sure to install a compatible version of Puppeteer (e.g., the latest).

**Comment by SujaanKanwar** [comment]
The incorrect version of Node was being used by me. It requires node@18 and I was on node@14. 
Thanks
