### ISSUE TITLE
Version update 

### ISSUE THREAD

**Issue by mrzaiffi** [puppeteer/replay#901]
## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:

**Comment by MohsenYousefzadeh** [comment]
> ## Expected Behavior
> 
> 
> 
> ## Actual Behavior
> 
> 
> 
> ## Steps to Reproduce the Problem
> 
> 
> 
> 1.
> 
> 1.
> 
> 1.
> 
> 
> 
> ## Specifications
> 
> 
> 
> - Version:
> 
> - Platform:
> 
>

**Comment by MohsenYousefzadeh** [comment]
> > ## Expected Behavior
> > 
> > 
> > 
> > ## Actual Behavior
> > 
> > 
> > 
> > ## Steps to Reproduce the Problem
> > 
> > 
> > 
> > 1.
> > 
> > 1.
> > 
> > 1.
> > 
> > 
> > 
> > ## Specifications
> > 
> > 
> > 
> > - Version:
> > 
> > - Platform:
> > 
> > 
> 
>
